// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RepoLens.Infrastructure;

#nullable disable

namespace RepoLens.Infrastructure.Migrations
{
    [DbContext(typeof(RepoLensDbContext))]
    [Migration("20260327131750_RestoreVocabularyIntelligence")]
    partial class RestoreVocabularyIntelligence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("RepoLens.Core.Entities.Artifact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RepositoryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "Path")
                        .IsUnique();

                    b.ToTable("Artifacts");
                });

            modelBuilder.Entity("RepoLens.Core.Entities.ArtifactVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtifactId")
                        .HasColumnType("integer");

                    b.Property<string>("CommitSha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StoredAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ArtifactId", "ContentHash")
                        .IsUnique();

                    b.ToTable("ArtifactVersions");
                });

            modelBuilder.Entity("RepoLens.Core.Entities.BusinessConcept", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BusinessPurposes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConceptType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Domain")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Keywords")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Properties")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RelatedTermIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RepositoryId")
                        .HasColumnType("integer");

                    b.Property<string>("TechnicalMappings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConceptType");

                    b.HasIndex("Domain");

                    b.HasIndex("RepositoryId");

                    b.ToTable("BusinessConcepts");
                });

            modelBuilder.Entity("RepoLens.Core.Entities.CodeElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessModifier")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("Complexity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Documentation")
                        .HasColumnType("text");

                    b.Property<string>("ElementType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EndLine")
                        .HasColumnType("integer");

                    b.Property<int>("FileId")
                        .HasColumnType("integer");

                    b.Property<string>("FullyQualifiedName")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsAsync")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsStatic")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Parameters")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReturnType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Signature")
                        .HasColumnType("text");

                    b.Property<int>("StartLine")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ElementType");

                    b.HasIndex("FileId");

                    b.HasIndex("Name");

                    b.ToTable("CodeElements");
                });

            modelBuilder.Entity("RepoLens.Core.Entities.Commit", b =>
                {
                    b.Property<string>("Sha")
                        .HasColumnType("text");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RepositoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Sha");

                    b.HasIndex("RepositoryId", "Sha")
                        .IsUnique();

                    b.ToTable("Commits");
                });

            modelBuilder.Entity("RepoLens.Core.Entities.ContributorMetrics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageCommitSize")
                        .HasColumnType("double precision");

                    b.Property<double>("AvgCommitMessageLength")
                        .HasColumnType("double precision");

                    b.Property<int>("BugFixCommits")
                        .HasColumnType("integer");

                    b.Property<double>("CodeOwnershipPercentage")
                        .HasColumnType("double precision");

                    b.Property<int>("CodeReviewComments")
                        .HasColumnType("integer");

                    b.Property<int>("CommitCount")
                        .HasColumnType("integer");

                    b.Property<double>("CommitFrequency")
                        .HasColumnType("double precision");

                    b.Property<double>("CommitMessageQualityScore")
                        .HasColumnType("double precision");

                    b.Property<double>("ContributionPercentage")
                        .HasColumnType("double precision");

                    b.Property<string>("ContributorEmail")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ContributorName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("CurrentCommitStreak")
                        .HasColumnType("integer");

                    b.Property<int>("DaysActive")
                        .HasColumnType("integer");

                    b.Property<int>("DocumentationCommits")
                        .HasColumnType("integer");

                    b.Property<int>("FeatureCommits")
                        .HasColumnType("integer");

                    b.Property<string>("FileTypeContributions")
                        .HasColumnType("TEXT");

                    b.Property<int>("FilesAdded")
                        .HasColumnType("integer");

                    b.Property<int>("FilesDeleted")
                        .HasColumnType("integer");

                    b.Property<int>("FilesModified")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FirstContribution")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("HourlyActivityPattern")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCoreContributor")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsNewContributor")
                        .HasColumnType("boolean");

                    b.Property<int>("IssuesCreated")
                        .HasColumnType("integer");

                    b.Property<int>("IssuesResolved")
                        .HasColumnType("integer");

                    b.Property<string>("LanguageContributions")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastContribution")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LinesAdded")
                        .HasColumnType("integer");

                    b.Property<int>("LinesDeleted")
                        .HasColumnType("integer");

                    b.Property<int>("LinesModified")
                        .HasColumnType("integer");

                    b.Property<int>("LongestCommitStreak")
                        .HasColumnType("integer");

                    b.Property<int>("MentionedInCommits")
                        .HasColumnType("integer");

                    b.Property<string>("MonthlyActivityPattern")
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnedFiles")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PeriodEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PeriodStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PullRequestsCreated")
                        .HasColumnType("integer");

                    b.Property<int>("PullRequestsReviewed")
                        .HasColumnType("integer");

                    b.Property<int>("RefactoringCommits")
                        .HasColumnType("integer");

                    b.Property<int>("RepositoryId")
                        .HasColumnType("integer");

                    b.Property<double>("RetentionScore")
                        .HasColumnType("double precision");

                    b.Property<int>("UniqueFilesTouched")
                        .HasColumnType("integer");

                    b.Property<string>("WeeklyActivityPattern")
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkingDays")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "ContributorEmail", "PeriodStart")
                        .IsUnique();

                    b.ToTable("ContributorMetrics");
                });

            modelBuilder.Entity("RepoLens.Core.Entities.FileMetrics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageMethodLength")
                        .HasColumnType("double precision");

                    b.Property<int>("BlankLineCount")
                        .HasColumnType("integer");

                    b.Property<double>("BugProneness")
                        .HasColumnType("double precision");

                    b.Property<double>("ChangeFrequency")
                        .HasColumnType("double precision");

                    b.Property<string>("ChangePatterns")
                        .HasColumnType("TEXT");

                    b.Property<double>("ChurnRate")
                        .HasColumnType("double precision");

                    b.Property<int>("ClassCount")
                        .HasColumnType("integer");

                    b.Property<int>("CodeSmellCount")
                        .HasColumnType("integer");

                    b.Property<double>("CognitiveComplexity")
                        .HasColumnType("double precision");

                    b.Property<double>("CohesionLevel")
                        .HasColumnType("double precision");

                    b.Property<double>("CommentDensity")
                        .HasColumnType("double precision");

                    b.Property<int>("CommentLineCount")
                        .HasColumnType("integer");

                    b.Property<int>("CommitsLastMonth")
                        .HasColumnType("integer");

                    b.Property<int>("CommitsLastQuarter")
                        .HasColumnType("integer");

                    b.Property<bool>("ContainsSensitiveData")
                        .HasColumnType("boolean");

                    b.Property<string>("ContributorBreakdown")
                        .HasColumnType("TEXT");

                    b.Property<double>("CouplingFactor")
                        .HasColumnType("double precision");

                    b.Property<int>("CriticalIssues")
                        .HasColumnType("integer");

                    b.Property<double>("CyclomaticComplexity")
                        .HasColumnType("double precision");

                    b.Property<string>("DependencyGraph")
                        .HasColumnType("TEXT");

                    b.Property<double>("DocumentationCoverage")
                        .HasColumnType("double precision");

                    b.Property<int>("DuplicationLines")
                        .HasColumnType("integer");

                    b.Property<double>("DuplicationPercentage")
                        .HasColumnType("double precision");

                    b.Property<int>("EffectiveLineCount")
                        .HasColumnType("integer");

                    b.Property<int>("ExternalLibraryReferences")
                        .HasColumnType("integer");

                    b.Property<string>("FileCategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FirstCommit")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FunctionCount")
                        .HasColumnType("integer");

                    b.Property<bool>("HasDocumentationComments")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasSecurityAnnotations")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasUnitTests")
                        .HasColumnType("boolean");

                    b.Property<int>("IncomingDependencies")
                        .HasColumnType("integer");

                    b.Property<bool>("IsBinaryFile")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsColdspot")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsConfigurationFile")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGeneratedCode")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsHotspot")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTestFile")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsThirdParty")
                        .HasColumnType("boolean");

                    b.Property<string>("IssueHistory")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastAnalyzed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastCommit")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LineCount")
                        .HasColumnType("integer");

                    b.Property<int>("LinesAdded")
                        .HasColumnType("integer");

                    b.Property<int>("LinesDeleted")
                        .HasColumnType("integer");

                    b.Property<double>("MaintainabilityIndex")
                        .HasColumnType("double precision");

                    b.Property<double>("MaintenanceEffort")
                        .HasColumnType("double precision");

                    b.Property<int>("MajorIssues")
                        .HasColumnType("integer");

                    b.Property<double>("MaturityScore")
                        .HasColumnType("double precision");

                    b.Property<double>("MaxMethodLength")
                        .HasColumnType("double precision");

                    b.Property<int>("MethodCount")
                        .HasColumnType("integer");

                    b.Property<int>("MinorIssues")
                        .HasColumnType("integer");

                    b.Property<double>("NestingDepth")
                        .HasColumnType("double precision");

                    b.Property<int>("OutgoingDependencies")
                        .HasColumnType("integer");

                    b.Property<string>("PrimaryLanguage")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("RefactoringPriority")
                        .HasColumnType("double precision");

                    b.Property<int>("RepositoryId")
                        .HasColumnType("integer");

                    b.Property<int>("SecurityHotspots")
                        .HasColumnType("integer");

                    b.Property<double>("StabilityScore")
                        .HasColumnType("double precision");

                    b.Property<double>("TechnicalDebtMinutes")
                        .HasColumnType("double precision");

                    b.Property<int>("TestCount")
                        .HasColumnType("integer");

                    b.Property<double>("TestCoverage")
                        .HasColumnType("double precision");

                    b.Property<int>("TimesMoved")
                        .HasColumnType("integer");

                    b.Property<int>("TimesRenamed")
                        .HasColumnType("integer");

                    b.Property<int>("TotalCommits")
                        .HasColumnType("integer");

                    b.Property<int>("UniqueContributors")
                        .HasColumnType("integer");

                    b.Property<int>("VulnerabilityCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "FilePath")
                        .IsUnique();

                    b.ToTable("FileMetrics");
                });

            modelBuilder.Entity("RepoLens.Core.Entities.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Settings")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("RepoLens.Core.Entities.Repository", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("AuthTokenReference")
                        .HasColumnType("text");

                    b.Property<bool>("AutoSync")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultBranch")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("IsPrivate")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastAnalysisAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastSyncCommit")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<int>("ProviderType")
                        .HasColumnType("integer");

                    b.Property<string>("ScanErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("ScanStatus")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("SyncErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("SyncIntervalMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalFiles")
                        .HasColumnType("integer");

                    b.Property<int>("TotalLines")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Username")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("OwnerId");

                    b.HasIndex("Url")
                        .IsUnique();

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("RepoLens.Core.Entities.RepositoryFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LineCount")
                        .HasColumnType("integer");

                    b.Property<string>("ProcessingStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ProcessingTime")
                        .HasColumnType("integer");

                    b.Property<int>("RepositoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FileExtension");

                    b.HasIndex("Language");

                    b.HasIndex("ProcessingStatus");

                    b.HasIndex("RepositoryId", "FilePath")
                        .IsUnique();

                    b.ToTable("RepositoryFiles");
                });

            modelBuilder.Entity("RepoLens.Core.Entities.RepositoryMetrics", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ActiveContributors")
                        .HasColumnType("integer");

                    b.Property<double>("ApiDocumentationCoverage")
                        .HasColumnType("double precision");

                    b.Property<double>("AverageClassSize")
                        .HasColumnType("double precision");

                    b.Property<double>("AverageCommitSize")
                        .HasColumnType("double precision");

                    b.Property<double>("AverageCyclomaticComplexity")
                        .HasColumnType("double precision");

                    b.Property<double>("AverageFileSize")
                        .HasColumnType("double precision");

                    b.Property<double>("AverageMethodLength")
                        .HasColumnType("double precision");

                    b.Property<int>("BinaryFileCount")
                        .HasColumnType("integer");

                    b.Property<int>("BlankLines")
                        .HasColumnType("integer");

                    b.Property<double>("BranchCoveragePercentage")
                        .HasColumnType("double precision");

                    b.Property<double>("BuildSuccessRate")
                        .HasColumnType("double precision");

                    b.Property<double>("BusFactor")
                        .HasColumnType("double precision");

                    b.Property<double>("CodeOwnershipConcentration")
                        .HasColumnType("double precision");

                    b.Property<int>("CodeSmells")
                        .HasColumnType("integer");

                    b.Property<double>("CognitiveComplexity")
                        .HasColumnType("double precision");

                    b.Property<int>("CommentLines")
                        .HasColumnType("integer");

                    b.Property<double>("CommentRatio")
                        .HasColumnType("double precision");

                    b.Property<int>("CommitsLastMonth")
                        .HasColumnType("integer");

                    b.Property<int>("CommitsLastQuarter")
                        .HasColumnType("integer");

                    b.Property<int>("CommitsLastWeek")
                        .HasColumnType("integer");

                    b.Property<int>("CriticalVulnerabilities")
                        .HasColumnType("integer");

                    b.Property<string>("DailyActivityPattern")
                        .HasColumnType("TEXT");

                    b.Property<double>("DevelopmentVelocity")
                        .HasColumnType("double precision");

                    b.Property<double>("DocumentationCoverage")
                        .HasColumnType("double precision");

                    b.Property<double>("DuplicationPercentage")
                        .HasColumnType("double precision");

                    b.Property<int>("EffectiveLinesOfCode")
                        .HasColumnType("integer");

                    b.Property<string>("FileTypeDistribution")
                        .HasColumnType("TEXT");

                    b.Property<int>("FilesChangedLastWeek")
                        .HasColumnType("integer");

                    b.Property<double>("FunctionCoveragePercentage")
                        .HasColumnType("double precision");

                    b.Property<double>("HalsteadDifficulty")
                        .HasColumnType("double precision");

                    b.Property<double>("HalsteadVolume")
                        .HasColumnType("double precision");

                    b.Property<string>("HourlyActivityPattern")
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageDistribution")
                        .HasColumnType("TEXT");

                    b.Property<double>("LineCoveragePercentage")
                        .HasColumnType("double precision");

                    b.Property<int>("LinesAddedLastWeek")
                        .HasColumnType("integer");

                    b.Property<int>("LinesDeletedLastWeek")
                        .HasColumnType("integer");

                    b.Property<double>("MaintainabilityIndex")
                        .HasColumnType("double precision");

                    b.Property<int>("MaxCyclomaticComplexity")
                        .HasColumnType("integer");

                    b.Property<int>("MaxDirectoryDepth")
                        .HasColumnType("integer");

                    b.Property<DateTime>("MeasurementDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OutdatedDependencies")
                        .HasColumnType("integer");

                    b.Property<int>("QualityGateFailures")
                        .HasColumnType("integer");

                    b.Property<int>("ReadmeWordCount")
                        .HasColumnType("integer");

                    b.Property<int>("RepositoryId")
                        .HasColumnType("integer");

                    b.Property<long>("RepositorySizeBytes")
                        .HasColumnType("bigint");

                    b.Property<int>("SecurityVulnerabilities")
                        .HasColumnType("integer");

                    b.Property<double>("TechnicalDebtHours")
                        .HasColumnType("double precision");

                    b.Property<double>("TestPassRate")
                        .HasColumnType("double precision");

                    b.Property<double>("TestToCodeRatio")
                        .HasColumnType("double precision");

                    b.Property<int>("TextFileCount")
                        .HasColumnType("integer");

                    b.Property<int>("TotalClasses")
                        .HasColumnType("integer");

                    b.Property<int>("TotalContributors")
                        .HasColumnType("integer");

                    b.Property<int>("TotalDependencies")
                        .HasColumnType("integer");

                    b.Property<int>("TotalDirectories")
                        .HasColumnType("integer");

                    b.Property<int>("TotalFiles")
                        .HasColumnType("integer");

                    b.Property<int>("TotalLinesOfCode")
                        .HasColumnType("integer");

                    b.Property<int>("TotalMethods")
                        .HasColumnType("integer");

                    b.Property<int>("VulnerableDependencies")
                        .HasColumnType("integer");

                    b.Property<int>("WikiPageCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "MeasurementDate")
                        .IsUnique();

                    b.ToTable("RepositoryMetrics");
                });

            modelBuilder.Entity("RepoLens.Core.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("RepoLens.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Preferences")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("OrganizationId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("RepoLens.Core.Entities.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("AssignedByUserId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("AssignedByUserId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("RepoLens.Core.Entities.VocabularyLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContextDescription")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ContextType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EndColumn")
                        .HasColumnType("integer");

                    b.Property<int>("EndLine")
                        .HasColumnType("integer");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("FoundAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StartColumn")
                        .HasColumnType("integer");

                    b.Property<int>("StartLine")
                        .HasColumnType("integer");

                    b.Property<string>("SurroundingCode")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("VocabularyTermId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FilePath");

                    b.HasIndex("VocabularyTermId");

                    b.ToTable("VocabularyLocations");
                });

            modelBuilder.Entity("RepoLens.Core.Entities.VocabularyStats", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageRelevanceScore")
                        .HasColumnType("double precision");

                    b.Property<double>("BusinessTechnicalRatio")
                        .HasColumnType("double precision");

                    b.Property<int>("BusinessTerms")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeprecatedTerms")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DomainDistribution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DomainSpecificTerms")
                        .HasColumnType("integer");

                    b.Property<string>("EmergingTerms")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LanguageDistribution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RepositoryId")
                        .HasColumnType("integer");

                    b.Property<string>("SourceDistribution")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TechnicalTerms")
                        .HasColumnType("integer");

                    b.Property<string>("TopDomains")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalTerms")
                        .HasColumnType("integer");

                    b.Property<int>("UniqueTerms")
                        .HasColumnType("integer");

                    b.Property<double>("VocabularyDensity")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId")
                        .IsUnique();

                    b.ToTable("VocabularyStats");
                });

            modelBuilder.Entity("RepoLens.Core.Entities.VocabularyTerm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("BusinessRelevance")
                        .HasColumnType("double precision");

                    b.Property<string>("Context")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Definition")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Domain")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("FirstSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Frequency")
                        .HasColumnType("integer");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedTerm")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RelatedTerms")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("RelevanceScore")
                        .HasColumnType("double precision");

                    b.Property<int>("RepositoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Synonyms")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TechnicalRelevance")
                        .HasColumnType("double precision");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TermType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UsageExamples")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Domain");

                    b.HasIndex("RelevanceScore");

                    b.HasIndex("Source");

                    b.HasIndex("TermType");

                    b.HasIndex("RepositoryId", "NormalizedTerm")
                        .IsUnique();

                    b.ToTable("VocabularyTerms");
                });

            modelBuilder.Entity("RepoLens.Core.Entities.VocabularyTermRelationship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CoOccurrenceCount")
                        .HasColumnType("integer");

                    b.Property<string>("Context")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Evidence")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FromTermId")
                        .HasColumnType("integer");

                    b.Property<string>("RelationshipType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Strength")
                        .HasColumnType("double precision");

                    b.Property<int>("ToTermId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RelationshipType");

                    b.HasIndex("ToTermId");

                    b.HasIndex("FromTermId", "ToTermId")
                        .IsUnique();

                    b.ToTable("VocabularyTermRelationships");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("RepoLens.Core.Entities.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("RepoLens.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("RepoLens.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("RepoLens.Core.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RepoLens.Core.Entities.Artifact", b =>
                {
                    b.HasOne("RepoLens.Core.Entities.Repository", null)
                        .WithMany("Artifacts")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RepoLens.Core.Entities.BusinessConcept", b =>
                {
                    b.HasOne("RepoLens.Core.Entities.Repository", "Repository")
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("RepoLens.Core.Entities.CodeElement", b =>
                {
                    b.HasOne("RepoLens.Core.Entities.RepositoryFile", "RepositoryFile")
                        .WithMany("CodeElements")
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RepositoryFile");
                });

            modelBuilder.Entity("RepoLens.Core.Entities.ContributorMetrics", b =>
                {
                    b.HasOne("RepoLens.Core.Entities.Repository", null)
                        .WithMany("ContributorMetrics")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RepoLens.Core.Entities.FileMetrics", b =>
                {
                    b.HasOne("RepoLens.Core.Entities.Repository", null)
                        .WithMany("FileMetrics")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RepoLens.Core.Entities.Repository", b =>
                {
                    b.HasOne("RepoLens.Core.Entities.Organization", "Organization")
                        .WithMany("Repositories")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RepoLens.Core.Entities.User", "Owner")
                        .WithMany("OwnedRepositories")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Organization");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("RepoLens.Core.Entities.RepositoryFile", b =>
                {
                    b.HasOne("RepoLens.Core.Entities.Repository", "Repository")
                        .WithMany("RepositoryFiles")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("RepoLens.Core.Entities.RepositoryMetrics", b =>
                {
                    b.HasOne("RepoLens.Core.Entities.Repository", null)
                        .WithMany("Metrics")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RepoLens.Core.Entities.User", b =>
                {
                    b.HasOne("RepoLens.Core.Entities.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("RepoLens.Core.Entities.UserRole", b =>
                {
                    b.HasOne("RepoLens.Core.Entities.User", "AssignedByUser")
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RepoLens.Core.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RepoLens.Core.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedByUser");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RepoLens.Core.Entities.VocabularyLocation", b =>
                {
                    b.HasOne("RepoLens.Core.Entities.VocabularyTerm", "VocabularyTerm")
                        .WithMany("Locations")
                        .HasForeignKey("VocabularyTermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VocabularyTerm");
                });

            modelBuilder.Entity("RepoLens.Core.Entities.VocabularyStats", b =>
                {
                    b.HasOne("RepoLens.Core.Entities.Repository", "Repository")
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("RepoLens.Core.Entities.VocabularyTerm", b =>
                {
                    b.HasOne("RepoLens.Core.Entities.Repository", "Repository")
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("RepoLens.Core.Entities.VocabularyTermRelationship", b =>
                {
                    b.HasOne("RepoLens.Core.Entities.VocabularyTerm", "FromTerm")
                        .WithMany("FromRelationships")
                        .HasForeignKey("FromTermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RepoLens.Core.Entities.VocabularyTerm", "ToTerm")
                        .WithMany("ToRelationships")
                        .HasForeignKey("ToTermId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromTerm");

                    b.Navigation("ToTerm");
                });

            modelBuilder.Entity("RepoLens.Core.Entities.Organization", b =>
                {
                    b.Navigation("Repositories");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("RepoLens.Core.Entities.Repository", b =>
                {
                    b.Navigation("Artifacts");

                    b.Navigation("ContributorMetrics");

                    b.Navigation("FileMetrics");

                    b.Navigation("Metrics");

                    b.Navigation("RepositoryFiles");
                });

            modelBuilder.Entity("RepoLens.Core.Entities.RepositoryFile", b =>
                {
                    b.Navigation("CodeElements");
                });

            modelBuilder.Entity("RepoLens.Core.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("RepoLens.Core.Entities.User", b =>
                {
                    b.Navigation("OwnedRepositories");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("RepoLens.Core.Entities.VocabularyTerm", b =>
                {
                    b.Navigation("FromRelationships");

                    b.Navigation("Locations");

                    b.Navigation("ToRelationships");
                });
#pragma warning restore 612, 618
        }
    }
}
